# DATA TRANFORMATION

## Step 1: Load Cleaned Tables

In [5]:
import pandas as pd
from pathlib import Path

PROCESSED = Path("../data/processed")

date_cols = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier"
    "_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date",
]

orders = pd.read_csv(PROCESSED / "orders_clean.csv", parse_dates=date_cols)
items = pd.read_csv(PROCESSED / "order_items_clean.csv")
payments = pd.read_csv(PROCESSED / "payments_clean.csv")
products = pd.read_csv(PROCESSED / "products_clean.csv")
sellers = pd.read_csv(PROCESSED / "sellers_clean.csv")
customers = pd.read_csv(PROCESSED / "customers_clean.csv")

for name, df in [("orders", orders), ("order_items", items), ("payments", payments),
                 ("products", products), ("sellers", sellers), ("customers", customers)]:
    print(f"{name:12} rows: {len(df):>8,}")

print("\nPurchase date type:", orders["order_purchase_timestamp"].dtype)

orders       rows:   99,441
order_items  rows:  112,650
payments     rows:  103,886
products     rows:   32,951
sellers      rows:    3,095
customers    rows:   99,441

Purchase date type: datetime64[ns]

# Transform Payments to Order-Level Paid Totals

In [6]:
# Transform order_items to one row per order

items_agg = (
    items.groupby("order_id")
    .agg(
        total_price=("price", "sum"),
        total_freight=("freight_value", "sum"),
        item_count=("order_item_id", "count"),
        seller_count=("seller_id", "nunique"),
    )
    .reset_index()
)

# Expected amount = total product price + total freight
items_agg["expected_total"] = items_agg["total_price"] + items_agg["total_freight"]

# Check the result
print("Rows in original order_items :", len(items))
print("Rows after aggregation       :", len(items_agg))
print("Unique order_id              :", items_agg["order_id"].nunique())

print("\nSample:")
display(items_agg.head())

Rows in original order_items : 112650
Rows after aggregation       : 98666
Unique order_id              : 98666

Sample:

,order_id,total_price,total_freight,item_count,seller_count,expected_total
0,00010242fe8c5a6d1ba2dd792cb16214,58.90,13.29,1,1,72.19
1,00018f77f2f0320c557190d7a144bdd3,239.90,19.93,1,1,259.83
2,000229ec398224ef6ca0657da4fc703e,199.00,17.87,1,1,216.87
3,00024acbcdf0a6daa1e931b038114c75,12.99,12.79,1,1,25.78
4,00042b26cf59d7ce69dfabb4e55b4fd9,199.90,18.14,1,1,218.04

# Create Final Order-Level Dataset

In [7]:
# Transform payments to one row per order

payments_agg = (
    payments.groupby("order_id")
    .agg(
        paid_total=("payment_value", "sum"),
        payment_count=("payment_sequential", "count"),
        max_installments=("payment_installments", "max"),
        main_payment_type=("payment_type", lambda s: s.value_counts().index[0]),
    )
    .reset_index()
)

# Check the result
print("Rows in original payments :", len(payments))
print("Rows after aggregation    :", len(payments_agg))
print("Unique order_id           :", payments_agg["order_id"].nunique())

print("\nSample:")
display(payments_agg.head())

Rows in original payments : 103886
Rows after aggregation    : 99440
Unique order_id           : 99440

Sample:

,order_id,paid_total,payment_count,max_installments,main_payment_type
0,00010242fe8c5a6d1ba2dd792cb16214,72.19,1,2,credit_card
1,00018f77f2f0320c557190d7a144bdd3,259.83,1,3,credit_card
2,000229ec398224ef6ca0657da4fc703e,216.87,1,5,credit_card
3,00024acbcdf0a6daa1e931b038114c75,25.78,1,2,credit_card
4,00042b26cf59d7ce69dfabb4e55b4fd9,218.04,1,3,credit_card

# # Create Final Order-Level Dataset

In [8]:
# Create Final Order-Level Dataset

reconciliation_data = (
    orders[
        [
            "order_id",
            "customer_id",
            "order_status",
            "order_purchase_timestamp",
            "order_delivered_customer_date",
            "order_estimated_delivery_date",
        ]
    ]
    .merge(items_agg, on="order_id", how="left")
    .merge(payments_agg, on="order_id", how="left")
)

print("Rows:", len(reconciliation_data))
print("Unique orders:", reconciliation_data["order_id"].nunique())

print("\nSample:")
display(reconciliation_data.head())

Rows: 99441
Unique orders: 99441

Sample:

,order_id,customer_id,order_status,order_purchase_timestamp,order_delivered_customer_date,order_estimated_delivery_date,total_price,total_freight,item_count,seller_count,expected_total,paid_total,payment_count,max_installments,main_payment_type
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-10 21:25:13,2017-10-18,29.99,8.72,1.0,1.0,38.71,38.71,3.0,1.0,voucher
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-08-07 15:27:45,2018-08-13,118.70,22.76,1.0,1.0,141.46,141.46,1.0,1.0,boleto
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-17 18:06:29,2018-09-04,159.90,19.22,1.0,1.0,179.12,179.12,1.0,3.0,credit_card
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-12-02 00:28:42,2017-12-15,45.00,27.20,1.0,1.0,72.20,72.20,1.0,1.0,credit_card
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-16 18:17:02,2018-02-26,19.90,8.72,1.0,1.0,28.62,28.62,1.0,1.0,credit_card

# Final Validation

In [9]:
print("Rows:", len(reconciliation_data))
print("Unique orders:", reconciliation_data["order_id"].nunique())

print("\nMissing values:")
print(
    reconciliation_data[
        ["expected_total", "paid_total"]
    ].isnull().sum()
)

print("\nDuplicate order_id:", reconciliation_data["order_id"].duplicated().sum())

print("\nData types:")
print(reconciliation_data.dtypes)

print("\nSample:")
display(reconciliation_data.head())

Rows: 99441
Unique orders: 99441

Missing values:
expected_total    775
paid_total          1
dtype: int64

Duplicate order_id: 0

Data types:
order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
total_price                             float64
total_freight                           float64
item_count                              float64
seller_count                            float64
expected_total                          float64
paid_total                              float64
payment_count                           float64
max_installments                        float64
main_payment_type                        object
dtype: object

Sample:

,order_id,customer_id,order_status,order_purchase_timestamp,order_delivered_customer_date,order_estimated_delivery_date,total_price,total_freight,item_count,seller_count,expected_total,paid_total,payment_count,max_installments,main_payment_type
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-10 21:25:13,2017-10-18,29.99,8.72,1.0,1.0,38.71,38.71,3.0,1.0,voucher
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-08-07 15:27:45,2018-08-13,118.70,22.76,1.0,1.0,141.46,141.46,1.0,1.0,boleto
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-17 18:06:29,2018-09-04,159.90,19.22,1.0,1.0,179.12,179.12,1.0,3.0,credit_card
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-12-02 00:28:42,2017-12-15,45.00,27.20,1.0,1.0,72.20,72.20,1.0,1.0,credit_card
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-16 18:17:02,2018-02-26,19.90,8.72,1.0,1.0,28.62,28.62,1.0,1.0,credit_card

In [10]:
missing_revenue = reconciliation_data[
    reconciliation_data["expected_total"].isnull()
    | reconciliation_data["paid_total"].isnull()
]

print("Orders with missing revenue values:", len(missing_revenue))

display(
    missing_revenue[
        [
            "order_id",
            "order_status",
            "expected_total",
            "paid_total"
        ]
    ].head(20)
)

Orders with missing revenue values: 776

,order_id,order_status,expected_total,paid_total
266,8e24261a7e58791d10cb1bf9da94df5c,unavailable,NaN,84.00
586,c272bcd21c287498b4883c7512019702,unavailable,NaN,97.68
687,37553832a3a89c9b2db59701c357ca67,unavailable,NaN,132.46
737,d57e15fb07fd180f06ab3926b39edcd2,unavailable,NaN,134.38
1130,00b1cb0320190ca0daa2c88b35206009,canceled,NaN,0.00
1160,2f634e2cebf8c0283e7ef0989f77d217,unavailable,NaN,615.53
1579,ee0db22a8e742b752914016708470ec8,unavailable,NaN,167.82
1801,ed3efbd3a87bea76c2812c66a0b32219,canceled,NaN,191.46
1826,6ad57aecbae806a7e9cc2cdb6b380711,unavailable,NaN,161.47
1868,df8282afe61008dc26c6c31011474d02,canceled,NaN,139.96
2029,8d4c637f1accf7a88a4555f02741e606,canceled,NaN,66.44
2148,9f3458f0433d4cfa472f4682654b8d49,unavailable,NaN,78.18
2161,7a9d4c7f9b068337875b95465330f2fc,canceled,NaN,72.90
2296,f0df036e9be21fc238f131bbfcdde769,unavailable,NaN,59.74
2316,86f0bcd9b426a2c1022ae317c7f27be6,unavailable,NaN,177.59
2680,98fe01bc254b759c1f2c11d77c2891d5,unavailable,NaN,199.06
2707,f56dc9034c3962e36d49fb73baa12800,unavailable,NaN,205.81
2971,0130f0f71fb0e831d18e6a3b33a3a50c,unavailable,NaN,52.77
3056,ddaec6fff982b13e7e048b627a11d6da,canceled,NaN,116.99
3084,84b8ba39037606b7b30a39d02e9e4154,unavailable,NaN,414.97

# Save Final Transformed Dataset

In [11]:

FINAL_PATH = PROCESSED / "reconciliation_data.csv"

reconciliation_data.to_csv(
    FINAL_PATH,
    index=False
)

print("Final dataset saved to:", FINAL_PATH)

Final dataset saved to: ..\data\processed\reconciliation_data.csv

# Loading into the Sql

In [12]:
from getpass import getpass
from urllib.parse import quote_plus
from sqlalchemy import create_engine, text

DB_PASSWORD = quote_plus(getpass("MySQL password: "))
engine = create_engine(f"mysql+pymysql://root:{DB_PASSWORD}@localhost/revenue_reconciliation")

In [13]:
with engine.connect() as connection:
    print("MySQL connection successful!")

MySQL connection successful!

In [ ]:
from sqlalchemy import text
from sqlalchemy.types import String

ID = String(32)

load_plan = {
    "orders": (orders, {
        "order_id": ID,
        "customer_id": ID,
        "order_status": String(20)
    }),

    "order_items": (items, {
        "order_id": ID,
        "product_id": ID,
        "seller_id": ID
    }),

    "payments": (payments, {
        "order_id": ID,
        "payment_type": String(20)
    }),

    "products": (products, {
        "product_id": ID
    }),

    "sellers": (sellers, {
        "seller_id": ID
    }),

    "customers": (customers, {
        "customer_id": ID
    }),

    "reconciliation": (reconciliation_data, {
        "order_id": ID,
        "customer_id": ID,
        "order_status": String(20),
        "main_payment_type": String(20)
    })
}

# Load data into MySQL
for table, (df, dtypes) in load_plan.items():
    df.to_sql(
        table,
        engine,
        if_exists="replace",
        index=False,
        dtype=dtypes,
        chunksize=10000
    )

# Create indexes
with engine.begin() as conn:
    conn.execute(text(
        "CREATE INDEX idx_orders_order_id ON orders (order_id)"
    ))
    conn.execute(text(
        "CREATE INDEX idx_items_order_id ON order_items (order_id)"
    ))
    conn.execute(text(
        "CREATE INDEX idx_payments_order_id ON payments (order_id)"
    ))
    conn.execute(text(
        "CREATE INDEX idx_products_product_id ON products (product_id)"
    ))
    conn.execute(text(
        "CREATE INDEX idx_recon_order_id ON reconciliation (order_id)"
    ))

# Verify row counts
with engine.connect() as conn:
    for table, (df, _) in load_plan.items():
        mysql_rows = conn.execute(
            text(f"SELECT COUNT(*) FROM {table}")
        ).scalar()

        status = "OK" if mysql_rows == len(df) else "MISMATCH"

        print(
            f"{table:15} "
            f"DataFrame: {len(df):>8,} | "
            f"MySQL: {mysql_rows:>8,} | {status}"
        )

In [ ]:
import numpy as np

d = reconciliation_data.copy()
diff = (d["paid_total"] - d["expected_total"]).round(2)

d["exception_class"] = np.select(
    [
        d["expected_total"].isnull() | d["paid_total"].isnull(),
        diff.abs() <= 1,
        diff > 1,
    ],
    ["Not Analyzable", "Matched", "Overpaid"],
    default="Underpaid",
)

print(d["exception_class"].value_counts())
print()
print(pd.crosstab(d["order_status"], d["exception_class"], margins=True))

NameError: name 'reconciliation_data' is not defined